### ISSUE TITLE
Calculator not fitting

### ISSUE THREAD

**Issue by pazuza1** [ericmuckley/QCMD_calculator#1]
Hi,
I am trying to run your program with default values and with the following package versions:
>>> numpy.__version__
'1.20.1'
>>> pandas.__version__
'1.2.4'
>>> shapely.__version__
'1.7.1'
>>> matplotlib.__version__
'3.3.4'

but I'm getting the following error:
204: UserWarning: Starting a Matplotlib GUI outside of the main thread will likely fail.
  df_cont_plot = plt.contour(
Traceback (most recent call last):
  File "C:\Users\VIP\Documents\QCMD_calculator-master\app.py", line 78, in run
    self.fn(*self.args, **self.kwargs)
  File "C:\Users\VIP\Documents\QCMD_calculator-master\app.py", line 204, in fit_model
    df_cont_plot = plt.contour(
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2567, in contour
    __ret = gca().contour(
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 6327, in contour
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py", line 816, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py", line 1430, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py", line 1501, in _contour_args
    self._process_contour_level_args(args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py", line 1171, in _process_contour_level_args
    if len(self.levels) > 1 and np.min(np.diff(self.levels)) <= 0.0:
TypeError: len() of unsized object

Not sure what the error might be. Maybe you could help?

Thanks

**Comment by ericmuckley** [comment]
I think this is a multiprocessing issue. Please see this answer, hopefully you can add multiprocessing to fix it.
https://stackoverflow.com/questions/34764535/why-cant-matplotlib-plot-in-a-different-thread

In the meantime, if you wish to try out the software, you can use this version which is hosted on Google Colab. The functionality is the same.
https://colab.research.google.com/drive/1d9ZwPXsqTKqsHDe2oNpe0DrLBiScH375?usp=sharing

**Comment by k0t1ka** [comment]
Amazing! Thank you so much. That works.

**Comment by pazuza1** [comment]
Amazing! Thank you so much. That works.
